version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: bookstore_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  postgres_test:
    image: postgres:15-alpine
    container_name: bookstore_db_test
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=bookstore_db_test
    ports:
    - "5433:5432"

volumes:
  postgres_data: